In [4]:
import pandas as pd

In [5]:
df=pd.read_csv("diabetes.csv")

In [7]:
df.head()

Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
0            6      148             72             35        0  33.6   
1            1       85             66             29        0  26.6   
2            8      183             64              0        0  23.3   
3            1       89             66             23       94  28.1   
4            0      137             40             35      168  43.1   

   DiabetesPedigreeFunction  Age  Outcome  
0                     0.627   50        1  
1                     0.351   31        0  
2                     0.672   32        1  
3                     0.167   21        0  
4                     2.288   33        1

In [14]:
df.shape

(768, 9)

In [17]:
df.Outcome.value_counts()

Outcome
0    500
1    268
Name: count, dtype: int64

In [18]:
# x=df.iloc[:,:-1]
x=df.drop('Outcome',axis='columns')

In [20]:
# y=df.iloc[:,-1:]
y=df.Outcome

In [27]:
from sklearn.preprocessing import StandardScaler

scaler=StandardScaler()
X=scaler.fit_transform(x)
X

array([[ 0.63994726,  0.84832379,  0.14964075, ...,  0.20401277,
         0.46849198,  1.4259954 ],
       [-0.84488505, -1.12339636, -0.16054575, ..., -0.68442195,
        -0.36506078, -0.19067191],
       [ 1.23388019,  1.94372388, -0.26394125, ..., -1.10325546,
         0.60439732, -0.10558415],
       ...,
       [ 0.3429808 ,  0.00330087,  0.14964075, ..., -0.73518964,
        -0.68519336, -0.27575966],
       [-0.84488505,  0.1597866 , -0.47073225, ..., -0.24020459,
        -0.37110101,  1.17073215],
       [-0.84488505, -0.8730192 ,  0.04624525, ..., -0.20212881,
        -0.47378505, -0.87137393]])

In [49]:
from sklearn.model_selection import train_test_split

X_train,X_test,Y_train,Y_test=train_test_split(X,y,test_size=.2,random_state=42,stratify=y)

In [50]:
from sklearn.tree import DecisionTreeClassifier
from sklearn.model_selection import cross_val_score

score= cross_val_score(DecisionTreeClassifier(),X,y,cv=5)

In [51]:
score

array([0.69480519, 0.68831169, 0.68831169, 0.80392157, 0.7254902 ])

In [52]:
# import numpy as np
score.mean()

0.7201680672268906

In [53]:
tree_classifier = DecisionTreeClassifier() 
tree_classifier.fit(X_train, Y_train)

DecisionTreeClassifier()

In [54]:
y_pred=tree_classifier.predict(X_test)

In [55]:
from sklearn.metrics import confusion_matrix,classification_report
print(confusion_matrix(Y_test,y_pred))
print(classification_report(Y_test,y_pred))

[[86 14]
 [28 26]]
              precision    recall  f1-score   support

           0       0.75      0.86      0.80       100
           1       0.65      0.48      0.55        54

    accuracy                           0.73       154
   macro avg       0.70      0.67      0.68       154
weighted avg       0.72      0.73      0.72       154



In [56]:
from sklearn.ensemble import BaggingClassifier

In [58]:
from sklearn.ensemble import BaggingClassifier
from sklearn.tree import DecisionTreeClassifier

# Define and train the bagging model
bag_model = BaggingClassifier(
    estimator=DecisionTreeClassifier(),   #
    n_estimators=100,
    max_samples=0.8,
    oob_score=True,
    random_state=0
)

# Train the model
bag_model.fit(X_train, Y_train)

# Check Out-of-Bag (OOB) score
bag_model.oob_score_


0.758957654723127

In [59]:
from sklearn.ensemble import RandomForestClassifier

score=cross_val_score(RandomForestClassifier(),X,y,cv=5)
score.mean()

0.77350819115525