In [84]:
import pandas as pd 
import numpy as np 
import  matplotlib.pyplot as plt 
import seaborn as sns 
%matplotlib inline

In [85]:
from sklearn.datasets import make_classification 

In [86]:
##crate the dataset 
X,y=make_classification(n_samples=1000,n_features=10,n_classes=2,random_state=3)

In [87]:
X

array([[ 1.72279572, -1.40443026, -0.47328436, ...,  1.16782981,
         1.31616247,  0.77080342],
       [ 1.1254387 ,  1.9530955 ,  0.94662962, ..., -0.16022298,
         1.29881994,  1.28847002],
       [-0.27470985,  0.26899326,  1.47533865, ..., -2.34680275,
         0.17553002,  0.07317341],
       ...,
       [ 0.44088259,  0.8368693 , -2.05140461, ..., -2.12860527,
        -0.27139323, -0.43212809],
       [-1.18301812, -0.16909228, -0.19492922, ...,  0.55320083,
        -1.58008063, -1.08030828],
       [ 0.36438365, -0.94252834,  0.07472719, ...,  0.29683316,
         1.41566571,  1.34055024]])

In [88]:
X

array([[ 1.72279572, -1.40443026, -0.47328436, ...,  1.16782981,
         1.31616247,  0.77080342],
       [ 1.1254387 ,  1.9530955 ,  0.94662962, ..., -0.16022298,
         1.29881994,  1.28847002],
       [-0.27470985,  0.26899326,  1.47533865, ..., -2.34680275,
         0.17553002,  0.07317341],
       ...,
       [ 0.44088259,  0.8368693 , -2.05140461, ..., -2.12860527,
        -0.27139323, -0.43212809],
       [-1.18301812, -0.16909228, -0.19492922, ...,  0.55320083,
        -1.58008063, -1.08030828],
       [ 0.36438365, -0.94252834,  0.07472719, ...,  0.29683316,
         1.41566571,  1.34055024]])

In [89]:
y

array([1, 0, 0, 1, 1, 0, 1, 1, 1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0,
       1, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 1, 1, 1, 0, 0, 0, 1, 0, 1, 1, 0,
       1, 1, 1, 0, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 0, 1, 0,
       0, 1, 0, 1, 0, 0, 0, 1, 1, 0, 1, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 1, 0, 1, 1, 1, 0, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0,
       1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 0, 1, 1, 0, 0,
       0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1, 0, 1,
       0, 0, 0, 1, 0, 1, 1, 1, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 1, 0, 1, 0,
       1, 1, 0, 0, 1, 0, 0, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 1, 0,
       0, 1, 1, 1, 1, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 1, 0, 1, 0, 1, 1,
       1, 1, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 1, 0, 1, 0, 1,
       0, 1, 1, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0,
       1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0, 0,

In [90]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.30, random_state=42)


In [91]:
from sklearn.linear_model import LogisticRegression
lr=LogisticRegression()

In [92]:
lr.fit(X_train,y_train)

LogisticRegression()

In [93]:
y_pred=lr.predict(X_test)
print(y_pred)

[0 0 1 1 1 1 0 0 1 1 1 1 0 0 0 0 0 1 1 1 1 0 1 1 1 0 0 0 0 1 1 0 0 1 0 1 1
 1 1 0 0 0 1 1 0 0 0 1 0 0 0 0 1 0 0 0 1 1 1 1 1 0 0 0 1 0 1 1 0 1 0 1 1 0
 1 0 0 1 1 0 0 0 1 1 0 0 1 1 1 1 1 0 1 1 1 1 1 0 0 0 1 1 0 1 1 1 0 1 0 1 1
 1 1 0 0 1 0 0 1 1 1 1 1 0 1 0 0 0 1 1 0 1 1 1 1 1 1 1 0 0 1 0 0 0 0 1 1 0
 0 1 0 0 0 0 1 1 0 1 0 1 0 1 1 0 1 1 1 1 0 0 0 0 1 1 0 0 0 0 0 0 0 0 1 0 1
 1 0 0 0 1 0 1 0 1 0 1 0 1 1 1 1 0 1 0 1 0 1 0 1 0 0 0 1 1 0 0 0 0 1 1 0 0
 0 0 0 0 1 0 1 1 1 0 0 1 1 1 1 1 1 1 1 0 1 0 1 1 0 0 0 1 0 1 0 0 0 0 0 0 1
 0 0 1 0 1 1 0 1 1 1 0 0 1 0 0 1 0 1 1 0 1 1 1 0 0 0 1 1 1 0 1 0 1 1 1 0 1
 0 1 1 1]


In [94]:
lr.predict_log_proba(X_test)

array([[-6.48073493e-02, -2.76856495e+00],
       [-1.50509575e-02, -4.20382971e+00],
       [-8.03407982e-01, -5.93845460e-01],
       [-1.45373434e+00, -2.66176265e-01],
       [-1.79252729e+00, -1.82168064e-01],
       [-1.26508654e+00, -3.31585020e-01],
       [-7.32970125e-02, -2.64966009e+00],
       [-7.36472745e-02, -2.64506579e+00],
       [-9.66539535e-01, -4.78676512e-01],
       [-3.04840228e+00, -4.85965667e-02],
       [-4.50680245e+00, -1.10950071e-02],
       [-2.54139078e+00, -8.20312061e-02],
       [-6.63812290e-03, -5.01824328e+00],
       [-5.11557433e-01, -9.15194022e-01],
       [-3.76026225e-01, -1.16022494e+00],
       [-2.31716568e-02, -3.77638889e+00],
       [-5.39325669e-04, -7.52546061e+00],
       [-1.95205655e+00, -1.53129943e-01],
       [-2.71759342e+00, -6.83146856e-02],
       [-9.25051195e-01, -5.05027663e-01],
       [-9.88289205e-01, -4.65554225e-01],
       [-9.04206085e-02, -2.44815273e+00],
       [-1.21605907e+00, -3.51539501e-01],
       [-3.

In [95]:
from sklearn.metrics import accuracy_score,confusion_matrix,classification_report

In [96]:
score=accuracy_score(y_test,y_pred)
print(score)
cm=confusion_matrix(y_test,y_pred)
print(cm)
print(classification_report(y_test,y_pred))

0.8833333333333333
[[131  21]
 [ 14 134]]
              precision    recall  f1-score   support

           0       0.90      0.86      0.88       152
           1       0.86      0.91      0.88       148

    accuracy                           0.88       300
   macro avg       0.88      0.88      0.88       300
weighted avg       0.88      0.88      0.88       300



In [97]:
print("y_test:", y_test[:10])   # first 10 true labels
print("y_pred:", y_pred[:10])   # first 10 predicted labels


y_test: [1 0 0 1 1 0 0 0 0 1]
y_pred: [0 0 1 1 1 1 0 0 1 1]


In [98]:
from sklearn.metrics import accuracy_score

accuracy = accuracy_score(y_test, y_pred)
print("Accuracy:", accuracy)


Accuracy: 0.8833333333333333


[[TN       FP]
 [FN       TP]]

TN (True Negatives): predicted 0 and was 0

TP (True Positives): predicted 1 and was 1

FP (False Positives): predicted 1 but was 0

FN (False Negatives): predicted 0 but was 1

In [99]:
from sklearn.metrics import confusion_matrix

cm = confusion_matrix(y_test, y_pred)
print("Confusion Matrix:\n", cm)



Confusion Matrix:
 [[131  21]
 [ 14 134]]


In [100]:
from sklearn.metrics import classification_report

print(classification_report(y_test, y_pred))


              precision    recall  f1-score   support

           0       0.90      0.86      0.88       152
           1       0.86      0.91      0.88       148

    accuracy                           0.88       300
   macro avg       0.88      0.88      0.88       300
weighted avg       0.88      0.88      0.88       300



 ### HYPERPARAMETER TUNING AND CROSS VALIDATION

In [101]:
model= LogisticRegression()
penalty= ['l1','l2','elasticnet']
c_vlaues=[100,10,1.0,0.1,0.01]
solver=[ 'newton_cg', 'lbfgs','newton_cholesky', 'sag', 'saga']


In [102]:
params= dict(penalty=penalty,C=c_vlaues,solver=solver)

In [103]:
params

{'penalty': ['l1', 'l2', 'elasticnet'],
 'C': [100, 10, 1.0, 0.1, 0.01],
 'solver': ['newton_cg', 'lbfgs', 'newton_cholesky', 'sag', 'saga']}

In [104]:
from sklearn.model_selection import StratifiedKFold
cv=StratifiedKFold()

In [105]:
#Grid_search
from sklearn.model_selection import GridSearchCV
grid=GridSearchCV(estimator=model,param_grid=params,scoring='accuracy',cv=cv,n_jobs=1)

In [106]:
grid

GridSearchCV(cv=StratifiedKFold(n_splits=5, random_state=None, shuffle=False),
             estimator=LogisticRegression(), n_jobs=1,
             param_grid={'C': [100, 10, 1.0, 0.1, 0.01],
                         'penalty': ['l1', 'l2', 'elasticnet'],
                         'solver': ['newton_cg', 'lbfgs', 'newton_cholesky',
                                    'sag', 'saga']},
             scoring='accuracy')

In [107]:
grid.fit(X_train,y_train)

C:\Users\Mustafa\anaconda3\Lib\site-packages\sklearn\linear_model\_sag.py:348: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
C:\Users\Mustafa\anaconda3\Lib\site-packages\sklearn\linear_model\_sag.py:348: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
C:\Users\Mustafa\anaconda3\Lib\site-packages\sklearn\linear_model\_sag.py:348: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
C:\Users\Mustafa\anaconda3\Lib\site-packages\sklearn\linear_model\_sag.py:348: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
C:\Users\Mustafa\anaconda3\Lib\site-packages\sklearn\linear_model\_sag.py:348: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
C:\Users\Mustafa\anaconda3\Lib\site-packages\sklearn\linear_model\_sag.py:348: ConvergenceWarning: T

GridSearchCV(cv=StratifiedKFold(n_splits=5, random_state=None, shuffle=False),
             estimator=LogisticRegression(), n_jobs=1,
             param_grid={'C': [100, 10, 1.0, 0.1, 0.01],
                         'penalty': ['l1', 'l2', 'elasticnet'],
                         'solver': ['newton_cg', 'lbfgs', 'newton_cholesky',
                                    'sag', 'saga']},
             scoring='accuracy')

In [108]:
grid.best_params_

{'C': 100, 'penalty': 'l1', 'solver': 'saga'}

In [109]:
grid.best_score_

0.8714285714285713

### Randomized SearchCV

In [110]:
from sklearn.model_selection import RandomizedSearchCV

In [113]:
model= LogisticRegression()
randomcv=RandomizedSearchCV(estimator=model,param_distributions=params,cv=5)

In [114]:
randomcv.fit(X_train,y_train)

C:\Users\Mustafa\anaconda3\Lib\site-packages\sklearn\model_selection\_validation.py:516: FitFailedWarning: 
35 fits failed out of a total of 50.
The score on these train-test partitions for these parameters will be set to nan.
If these failures are not expected, you can try to debug them by setting error_score='raise'.

Below are more details about the failures:
--------------------------------------------------------------------------------
10 fits failed with the following error:
Traceback (most recent call last):
  File "C:\Users\Mustafa\anaconda3\Lib\site-packages\sklearn\model_selection\_validation.py", line 859, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "C:\Users\Mustafa\anaconda3\Lib\site-packages\sklearn\base.py", line 1363, in wrapper
    return fit_method(estimator, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Mustafa\anaconda3\Lib\site-packages\sklearn\linear_model\_logistic.py", line 1220, in fit
    ra

RandomizedSearchCV(cv=5, estimator=LogisticRegression(),
                   param_distributions={'C': [100, 10, 1.0, 0.1, 0.01],
                                        'penalty': ['l1', 'l2', 'elasticnet'],
                                        'solver': ['newton_cg', 'lbfgs',
                                                   'newton_cholesky', 'sag',
                                                   'saga']})

In [115]:
randomcv.best_score_

0.8714285714285713

In [116]:
randomcv.best_params_

{'solver': 'sag', 'penalty': 'l2', 'C': 10}

# Logistic Regression for multiclass classification

In [117]:
##crate the dataset 
X,y=make_classification(n_samples=1000,n_features=10,n_informative=3,n_classes=3,random_state=3)

In [123]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.30, random_state=42)


In [124]:
from sklearn.linear_model import LogisticRegression
Lr=LogisticRegression(multi_class='ovr')
Lr.fit(X_train,y_train)
y_pred=Lr.predict(y_test)

In [125]:
Lr=LogisticRegression(multi_class='ovr')

In [127]:
Lr.fit(X_train,y_train)
y_pred=Lr.predict(X_test)

C:\Users\Mustafa\anaconda3\Lib\site-packages\sklearn\linear_model\_logistic.py:1273: FutureWarning: 'multi_class' was deprecated in version 1.5 and will be removed in 1.7. Use OneVsRestClassifier(LogisticRegression(..)) instead. Leave it to its default value to avoid this warning.
  warnings.warn(


In [129]:
print("y_test:", y_test[:10])   # first 10 true labels
print("y_pred:", y_pred[:10])   # first 10 predicted labels


y_test: [0 0 0 2 0 0 0 0 0 0]
y_pred: [0 1 2 2 2 2 2 1 0 1]


In [130]:
score=accuracy_score(y_test,y_pred)
print(score)
cm=confusion_matrix(y_test,y_pred)
print(cm)
print(classification_report(y_test,y_pred))

0.6366666666666667
[[48 25 28]
 [20 81  3]
 [19 14 62]]
              precision    recall  f1-score   support

           0       0.55      0.48      0.51       101
           1       0.68      0.78      0.72       104
           2       0.67      0.65      0.66        95

    accuracy                           0.64       300
   macro avg       0.63      0.64      0.63       300
weighted avg       0.63      0.64      0.63       300

